### ISSUE TITLE
Cannot Build Driver

### ISSUE THREAD

**Issue by JulesThuillier** [avafinger/gc2035#1]
Hi !
Your driver seems to be able to solve all my problems with controlling the GC2035 camera, but I cannot get to compile it on my Orange Pi PC + (H3) running Armbian.

I really a driver newbie, so it would be great if you could give more explanation about the "Building from source" part :)

Cheers,
Jules

**Comment by avafinger** [comment]
Hi Jules,

Latest Armbian has this GC2035 already compiled. Just pass the correct parameters for what you need.
