### ISSUE TITLE
The issue about load drivers

### ISSUE THREAD

**Issue by leongong1996** [avafinger/gc2035#5]
I have found the /dev/video0 when I executed these two command: 

modprobe  vfe_v4l2

modprobe  gc2035 hres=1

but when I try to open camera with opencv , It can not  start-up the camera.

**Comment by avafinger** [comment]
```
modprobe -r -v vfe_v4l2
modprobe -r -v gc2035
```
These commands **REMOVE** (unload) the drivers! 

* Boot your board and check /dev/video0 , if you see /dev/video, just use your opencv.

* if not then you must load the drivers with:
**modprobe gc2035 hres=1
modprobe vfe_v4l2**

**Comment by leongong1996** [comment]
sorry that I type the words error.I did execute these two command that you typed. And then I sawd /dev/video0, but the opencv didn't work.My program can run with USB camera. I wonder that if  my os has any effect on it.I use the Ubuntu 16.

**Comment by avafinger** [comment]
You can adapt this and check if the camera is working:
https://github.com/avafinger/cap-v4l2 (OpenCV) - adjust frame and size to gc2035
https://github.com/avafinger/guvcview (check if camera is working)

**Comment by leongong1996** [comment]
I have resolved it , thank you.
